GameMuster/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('games.urls')),
    path('profile/', include('profiles.urls')),
    path('api/', include('api.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

api/urls.py
from django.conf.urls import include
from django.urls import path

from api.views import GamesView, GameInfoView


app_name = 'api'

urlpatterns = [
    path('', GamesView.as_view()),
    path('<int:game_id>/', GameInfoView.as_view()),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

games/urls.py
from django.urls import path
from games import views


app_name = 'games'


urlpatterns = [
    path('', views.GameListView.as_view(), name='main_page'),
    path('game/<int:game_id>/', views.GameInfoView.as_view(), name='game_info'),
    path('add_to_favorite/<int:game_id>/', views.add_to_favorites_view, name='add_to_favorite'),
    path('remove_from_favorite/<int:game_id>/', views.remove_from_favorites_view, name='remove_from_favorite')
]

profiles/urls.py
from django.urls import path
from . import views


app_name = 'user_profile'


urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('<int:profile_id>/', views.profile_view, name='profile'),
    path('activate/uid=<str:uidb64>/token=<str:token>/', views.activation_view, name='activation'),
    path('edit/', views.EditProfileView.as_view(), name='edit_profile'),
    path('logout/', views.logout_view, name='logout')
]

games/models.py
from django.db import models

from profiles.models import Profile


class Game(models.Model):
    game_id = models.IntegerField(unique=True)
    game_name = models.CharField(max_length=200)
    cover_url = models.URLField(null=True)
    user_rating = models.IntegerField(null=True)
    user_rating_count = models.IntegerField(null=True)
    critic_rating = models.IntegerField(null=True)
    critic_rating_count = models.IntegerField(null=True)
    game_description = models.TextField(null=True)
    game_release_date = models.DateField(null=True)
    user_profiles = models.ManyToManyField(Profile, related_name='favorite_games')


class Keyword(models.Model):
    keyword_id = models.IntegerField(unique=True)
    keyword_name = models.CharField(max_length=100)
    games = models.ManyToManyField(Game, related_name='keywords')


class Genre(models.Model):
    genre_id = models.IntegerField(unique=True)
    genre_name = models.CharField(max_length=100)
    games = models.ManyToManyField(Game, related_name='genres')


class Platform(models.Model):
    platform_id = models.IntegerField(unique=True)
    platform_name = models.CharField(max_length=100)
    platform_abbreviation = models.CharField(max_length=20, null=True)
    games = models.ManyToManyField(Game, related_name='platforms')


class Screenshot(models.Model):
    screen_thumb_url = models.URLField()
    screen_big_url = models.URLField()
    game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name='screenshots', null=True)

games/forms.py
from django import forms


class SearchListForm(forms.Form):
    platform_choices = (
        ('PC', 'PC'),
        ('PS4', 'PS4'),
        ('XONE', 'Xbox One'),
        ('Switch', 'Nintendo switch')
    )
    genre_choices = (
        ('Strategy', 'Strategy'),
        ('Shooter', 'Shooter'),
        ('Role-playing (RPG)', 'RPG'),
        ('Platform', 'Platformer')
    )
    platforms = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(),
                                          choices=platform_choices)
    genres = forms.MultipleChoiceField(
        choices=genre_choices, widget=forms.CheckboxSelectMultiple)
    rating_lower_limit = forms.IntegerField(min_value=0, max_value=100)
    rating_upper_limit = forms.IntegerField(min_value=0, max_value=100)


class SearchNameForm(forms.Form):
    name = forms.CharField(max_length=100)

games/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotFound, HttpResponseBadRequest
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpRequest
from django.conf import settings
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect

from games.forms import SearchListForm, SearchNameForm
from games.igdb_api import IGDBClient
from games.twitter_api import TwitterApi
from games.models import Game


class GameInfoView(DetailView):
    model = Game
    template_name = 'Games/game.html'

    def get_object(self, **kwargs):
        return get_object_or_404(Game, game_id=self.kwargs['game_id'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        twitter_api_client = TwitterApi(
            settings.TWITTER_API_URL, settings.TWITTER_API_KEY, settings.TWITTER_SECRET_API_KEY)
        context['tweets'] = twitter_api_client.search_tweets(f'"{self.object.game_name}"')
        return context


class GameListView(ListView):
    api_client = IGDBClient(settings.IGDB_API_KEY, settings.IGDB_API_URL)
    model = Game
    paginate_by = settings.GAME_LIST_LIMIT
    template_name = 'Games/list.html'
    params = None

    def get_queryset(self, **kwargs):
        params = self._get_params(self.request.GET)
        return self._get_game_list(params)

    def get_context_data(self, *, object_list=None, **kwargs) -> HttpResponse:
        context = super().get_context_data(**kwargs)
        list_search_form = SearchListForm(self.request.GET)
        name_search_form = SearchNameForm(self.request.GET)
        context['list_search_form'] = list_search_form
        context['name_search_form'] = name_search_form
        GET = self.request.GET.copy()
        if GET.get('page'):
            GET.pop('page')
        context['params'] = GET.urlencode()
        return context

    def _get_params(self, request_dict) -> dict:
        MINIMUN_RATING = 0
        MAXIMUM_RATING = 100
        params = {}
        if request_dict.getlist('name'):
            params['name'] = request_dict.getlist('name')[0]
        else:
            params['platforms'] = request_dict.getlist('platforms')
            params['genres'] = request_dict.getlist('genres')
            params['rating_lower_limit'] = request_dict.getlist('rating_lower_limit', default=[MINIMUN_RATING])[0]
            params['rating_upper_limit'] = request_dict.getlist('rating_upper_limit', default=[MAXIMUM_RATING])[0]
        return params

    def _get_game_list(self, params: dict) -> Paginator:
        if params.get('name'):
            games = Game.objects.filter(game_name__icontains=params['name']).all()
            return games
        else:
            games = Game.objects.filter(user_rating__gte=int(params['rating_lower_limit']),
                                        user_rating__lte=int(params['rating_upper_limit'])).all()
            if params['platforms']:
                games = games.filter(platforms__platform_abbreviation__in=params['platforms']).all()
            if params['genres']:
                games = games.filter(genres__genre_name__in=params['genres']).all()
            games = games.distinct()
            return games


@login_required
def add_to_favorites_view(request: HttpRequest, game_id: HttpResponse):
    game = get_object_or_404(Game, id=game_id)
    game.user_profiles.add(request.user)
    game.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def remove_from_favorites_view(request: HttpRequest, game_id: int) -> HttpResponse:
    try:
        game = Game.objects.get(game_id=game_id)
    except Game.DoesNotExist:
        return HttpResponseNotFound()
    if request.user.is_in_favorite(game_id):
        game.user_profiles.remove(request.user)
        game.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return HttpResponseBadRequest()

games/templates/Games/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>

    <script src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css" />
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>

<body>
    <div class="container-fluid main-container">
        <nav class="navbar navbar-dark bg-danger navbar navbar-expand-lg">
            <a class="navbar-brand" href="{% url 'games:main_page' %}">
                <img src="{% static "img/game.png" %}" width="40" height="40" alt="">
                <span>GameMuster</span>
            </a>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup"></div>
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'user_profile:profile' user.id %}">
                                Profile
                        </a>
                        <a class="nav-item nav-link" href="{% url 'user_profile:logout' %}">
                                Logout
                        </a>
                    {% else %}
                        <a class="nav-item nav-link" href="{% url 'user_profile:sign_in' %}">Sign in</a>
                        <a class="nav-item nav-link" href="{% url 'user_profile:sign_up' %}">Sign up</a>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>
    <div class="container-fluid">
        {%  block content %}
        {% endblock %}
    </div>
</body>

</html>

games/templates/Games/game.html
{% extends "Games/base.html" %}
{% load static %}
{% load user_fav %}

{%block title%}
Info
{% endblock %}

{% block content %}
<div class="row">
    
    <div class="col-7 top-buffer mx-3">
        <div class="row">
            <h1>{{ game.game_name }}</h1>
            {% if user.is_authenticated %}
                {% is_favorite user game.game_id as in_fav %}
                {% if in_fav %}
                    <h1><a class="badge badge-danger mx-2" href="{% url 'games:remove_from_favorite' game.game_id %}">REMOVE</a></h1>
                {% else %}
                    <h1><a class="badge badge-success mx-2" href="{% url 'games:add_to_favorite' game.game_id %}">MUST</a></h1>
                {% endif %}
            {% endif %}
        </div>
        <div class="row"></div>
        <h2>Description</h2>
        <p class="text-break">
            {% if game.game_description %}
                {{ game.game_description }}
            {% else %}
                No description yet
            {% endif %}
        </p>
        <h2>Release date</h2>
        <p>{{ game.game_release_date }}</p>
        <h2>Screenshots</h2>
        <div class="d-flex flex-wrap">
            {% for screenshot in game.screenshots.all %}
                <img class="game-screen" src="{{ screenshot.screen_big_url }}" alt="{{ game.game_name }}" width="200px" height="200px">
            {% endfor %}
        </div>
    </div>

    <div class="col-2">
        <h2>Rating</h2>
        <h2><span class="badge badge-success game-rate">Users {{ game.user_rating }} ({{ game.user_rating_count }})</span></h2>
        <h2><span class="badge badge-danger game-rate">Critics {{ game.critic_rating }} ({{ game.critic_rating_count }})</span></h2>
        <h2>Genres</h2>
        <div class="row mx-1">
            {% for genre in game.genres.all %}
                <h2><span class="badge badge-danger mx-1">{{genre.genre_name}}</span></h2>
            {% endfor %}
        </div>
        <h2>Platforms</h2>
        <div class="row mx-1">
            {% for platform in game.platforms.all %}
                <h2><span class="badge badge-danger mx-1">{% if platform.abbreviation %}{{ platform.platform_abbreviation }}{% else %}{{ platform.platform_name }}{% endif %}</span></h2>
            {% endfor %}
        </div>
    </div>

    <div class="col">
        <h1>#{{ game.game_name }} Tweets</h1>
        <div>
            {% for tweet in tweets %}
            <div class="card bg-danger text-white mb-2 tweet">
                <div class="card-body">
                    <p class="card-text">{{ tweet.text }}</p>
                    <p class="card-link float-left">{{ tweet.creation_date }}</p>
                    <a href="http://{{ tweet.tweet_link }}" class="card-link text-right float-right">@{{ tweet.user_name }}</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

games/templates/Games/list.html
{% extends "Games/base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load user_fav %}

{%block title%}
Home
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-2" id="sidebar">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapseMenu"
            aria-controls="collapseMenu" aria-expanded="false" aria-label="Toggle navigation">
            <img src="{% static "img/arrow.png" %}" width="30" height="30">
        </button>

        <div class="collapse" id="collapseMenu">
            <form action="." class="bg-danger text-white collapse-menu" method="get">
                <div>
                    <p class="font-weight-bold">Platform:</p>
                    {{ list_search_form.platforms }}
                </div>
                <div>
                    <p class="font-weight-bold">Genres:</p>
                    {{ list_search_form.genres }}
                </div>
                <div>
                    <p class="font-weight-bold">User Rating:</p>

                    <div class="range-slider">
                        <input type="text" class="js-range-slider" value="" />
                    </div>
                    <div class="extra-controls">
                        {% render_field list_search_form.rating_lower_limit class="js-input-from" style="visibility:hidden"%}
                        {% render_field list_search_form.rating_upper_limit class="js-input-to" style="visibility:hidden"%}
                    </div>
                </div>
                <input type="submit" value="Submit">
            </form>
        </div>

    </div>

    <div class="col-8 top-buffer d-felx flex-wrap">

        <div class="md-form mt-0">
            <form action="." method="get">
                {% render_field name_search_form.name class="form-control" placeholder="Search" %}
            </form>
        </div>

        <div class="row top-buffer">
            {% for game in page_obj %}
            <div class="card game-card">
               <img src="{% if game.cover_url %}{{ game.cover_url }}{% else %}{% static 'img/no_img.jpg' %}{% endif %}"
                    class="card-img-top game_cover">
                <div class="card-body bg-dark text-white">
                    <h5>{{ game.game_name }}</h5>
                    <p class="card-text">
                        {% for keyword in game.keywords.all|slice:"0:2" %}
                        <span>{{ keyword.keyword_name }}</span>
                        {% endfor %}
                    </p>
                    <p class="card-text">
                        <span class="badge badge-pill badge-light"><a
                                href="{% url 'games:game_info' game.game_id %}">Open</a></span>
                         {% if user.is_authenticated %}
                             {% is_favorite user game.game_id as in_fav %}
                             {% if in_fav %}
                                <span class="badge badge-pill badge-light"><a href="{% url 'games:remove_from_favorite' game.game_id %}">Remove</a></span>
                             {% else %}
                                <span class="badge badge-pill badge-light"><a href="{% url 'games:add_to_favorite' game.game_id %}">Must</a></span>
                             {% endif %}
                         {% endif %}
                    </p>
                </div>
            </div>
            {% endfor %}
        </div>

        <nav class="mx-auto paginator" aria-label="...">
            <ul class="pagination pagination-lg">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link bg-danger text-white"
                            href="?page={{ page_obj.previous_page_number }}&{{params}}">{{ page_obj.previous_page_number }}</a></li>
                {% endif %}

                <li class="page-item disabled"><a class="page-link bg-danger text-white">{{page_obj.number}}</a></li>

                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link bg-danger text-white"
                        href="?page={{ page_obj.next_page_number }}&{{params}}">{{ page_obj.next_page_number }}</a></li>
                {% endif %}
            </ul>
        </nav>

    </div>

</div>

<script src="{% static "js/list.js" %}"></script>
{% endblock %}